### ISSUE TITLE
Phone number not working

### ISSUE THREAD

**Issue by ArtsiX** [Ezzpify/SteamAuthenticator#1]
I cannot use my Finland phone number... When I put my phone number. It just says: "Something bad happened..." Finland's phone numbers start with +358xxxxxxxxxx

**Comment by Ezzpify** [comment]
Try adding your phone number to your steam account manually, then attach the authenticator.

**Comment by Assuass99** [comment]
This happens to me too, please help.

**Comment by RoanDev** [comment]
@Ezzpify unfortunatelly it didnt help. Program still asks for a phone number :c
Trying on Poland number +48 729 427 921, this number cannot be formatted as +1 XXX-XXX-XXXX, only as +48 XXX-XXX-XXX(I've tried +4 8XX-XXX-XXXX - didnt work)

**Comment by Ezzpify** [comment]
Can you try with the new version? https://github.com/Ezzpify/SteamAuthenticator/releases
